# This is a basic workflow to help you get started with Actions

name: Actualizar perfiles.geojson

# Controls when the workflow will run
on:
   schedule:
     - cron: '0 0 * * SUN'  # "At 00:00 on Sunday."

  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Descarga perfiles.geojson y los mete en el repo
        run: |
          curl http://sisinta.inta.gob.ar/es/perfiles.geojson -f -o data-raw/perfiles.geojson
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit data-raw/perfiles.geojson -m 'Actualiza perfiles.geojson' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
